version: "3"
services:
  strapiDB:
    image: postgres:12.0-alpine
    container_name: strapi_pg_db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi

  minio:
    image: bitnami/minio:latest
    env_file: .env
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_ACCESS_SECRET}
      MINIO_DEFAULT_BUCKETS: ${AWS_BUCKET}
    networks:
      - strapi # Unifying networks

volumes:
  strapi-data:
  minio_data:
    driver: local

networks:
  strapi:
    name: Strapi
    driver: bridge
